### ISSUE TITLE
Support for issue transitions

### ISSUE THREAD

**Issue by mafrosis** [mafrosis/jira-offline#21]
Currently jiracli doesn't model a project's workflow, so there's no way to transition an issue from, say, `Backlog` to `Done`.

Jira manages this with a prescribed workflow, so only certain status transitions are valid. `jiracli` will also need to model these workflow transitions for a project in order to fix.

**Comment by shipperizer** [comment]
when is this gonna be done?been waiting for more than a year for this stuff bro, run out of VB

**Comment by mafrosis** [comment]
Pull requests welcome, check the collaborators guide
